spring.application.name=Cosmetics_Store_Backed

# Server configuration
spring.datasource.url=jdbc:mysql://localhost:3306/cosmeticsdb
spring.datasource.username=sa
spring.datasource.password=1

spring.data.mongodb.uri=mongodb://localhost:27017/cosmeticsdb
